Creator "igraph Thu May 23 00:23:33 2024"
Version 1
graph
[
  directed 0
  node
  [
    id 0
    name "AACGTAGGGTGCAAGCGTTGTCCGGAATTACTGGGTGTAAAGGGAGCGCAGGCGGACCGGCAAGTTGGAAGTGAAAACTATGGGCTCAACCCATAAATTGCTTTCAAAACTGCTGGCCTTGAGTAGTGCAGAGGTAGGTGGAATTCCCGGTGTAGCGGTGGAATGCGTAGATATCGGGAGGAACACCAGTGGCGAAGGCGACCTACTGGGCACCAACTGACGCTGAGGCTCGAAAGCATGGGTAGCAAACAGG"
  ]
  node
  [
    id 1
    name "TACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGTTTATTAAGTTAGTGGTTAAATATTTGAGCTAAACTCAATTGTGCCATTAATACTGGTAAACTGGAGTACAGACGAGGTAGGCGGAATAAGTTAAGTAGCGGTGAAATGCATAGATATAACTTAGAACTCCGATAGCGAAGGCAGCTTACCAGACTGTAACTGACGCTGATGCACGAGAGCGTGGGTAGCGAACAGG"
  ]
  node
  [
    id 2
    name "TACGTAGGGAGCGAGCGTTGTCCGGAATTACTGGGTGTAAAGGGAGCGTAGGCGGGAAAGCAAGTTGGAAGTGAAATGCATGGGCTTAACCCATGAGCTGCTTTCAAAACTGTTTTTCTTGAGTGAAGTAGAGGCAGGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCAGTGGCGAAGGCGGCCTGCTGGGCTTTAACTGACGCTGAGGCTCGAAAGCGTGGGTAGCAAACAGG"
  ]
  node
  [
    id 3
    name "AACGTAGGGTGCAAGCGTTGTCCGGAATTACTGGGTGTAAAGGGAGCGCAGGCGGGAAGACAAGTTGGAAGTGAAAACCATGGGCTCAACCCATGAATTGCTTTCAAAACTGTTTTTCTTGAGTAGTGCAGAGGTAGATGGAATTCCCGGTGTAGCGGTGGAATGCGTAGATATCGGGAGGAACACCAGTGGCGAAGGCGGTCTACTGGGCACCAACTGACGCTGAGGCTCGAAAGCATGGGTAGCAAACAGG"
  ]
  node
  [
    id 4
    name "TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGATTGTTAAGTCAGTTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGATACTGGCAGTCTTGAGTGCAGTAGAGGTGGGCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATTGCGAAGGCAGCTCACTGGAGTGTAACTGACGCTGATGCTCGAAAGTGTGGGTATCAAACAGG"
  ]
  node
  [
    id 5
    name "TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGTGCGTAGGTGGCAAGGCAAGTCAGATGTGAAAGCCCGGGGCTCAACCCCGGTACTGCATTTGAAACTGTCTAGCTAGAGTGCAGGAGAGGTAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCAGTGGCGAAGGCGGCTTACTGGACTGTAACTGACACTGAGGCACGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 6
    name "AACGTAGGTCACAAGCGTTGTCCGGAATTACTGGGTGTAAAGGGAGCGCAGGCGGGAAGACAAGTTGGAAGTGAAATCTATGGGCTCAACCCATAAACTGCTTTCAAAACTGTTTTTCTTGAGTAGTGCAGAGGTAGGCGGAATTCCCGGTGTAGCGGTGGAATGCGTAGATATCGGGAGGAACACCAGTGGCGAAGGCGGCCTACTGGGCACCAACTGACGCTGAGGCTCGAAAGTGTGGGTAGCAAACAGG"
  ]
  node
  [
    id 7
    name "TACGGAGGATCCAAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGTTTGATAAGTTAGAGGTGAAATACCGGGGCTCAACTCCGGAACTGCCTCTAATACTGTTGAACTAGAGAGTAGTTGCGGTAGGCGGAATGTATGGTGTAGCGGTGAAATGCTTAGAGATCATACAGAACACCGATTGCGAAGGCAGCTTACCAAACTATATCTGACGTTGAGGCACGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 8
    name "TACGTAGGGGGCGAGCGTTATCCGGATTCATTGGGCGTAAAGCGCGCGTAGGCGGCCCGTCAAGCGGAACCTCTAACCCGAGGGCTCAACCCCCGGTCGGGTTCCGAACTGGCAGGCTCGAGTTTGGTAGAGGAAGATGGAATTCCCGGTGTAGCGGTGGAATGCGCAGATATCGGGAAGAACACCGATGGCGAAGGCAGTCTTCTGGGCCATCAACTGACGCTGAGGCGCGAAAGCTGGGGGAGCGAACAGG"
  ]
  node
  [
    id 9
    name "TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGATGGATGTTTAAGTCAGTTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGATACTGGATATCTTGAGTGCAGTTGAGGCAGGCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATTGCGAAGGCAGCCTGCTAAGCTGCAACTGACATTGAGGCTCGAAAGTGTGGGTATCAAACAGG"
  ]
  node
  [
    id 10
    name "TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGACGCTTAAGTCAGTTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGATACTGGGTGTCTTGAGTACAGTAGAGGCAGGCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATTGCGAAGGCAGCCTGCTGGACTGTAACTGACGCTGATGCTCGAAAGTGTGGGTATCAAACAGG"
  ]
  node
  [
    id 11
    name "TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGTGGACAGTTAAGTCAGTTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGATACTGGCTGTCTTGAGTACAGTAGAGGTGGGCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATTGCGAAGGCAGCTCACTGGACTGCAACTGACACTGATGCTCGAAAGTGTGGGTATCAAACAGG"
  ]
  node
  [
    id 12
    name "TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCGACGCAAGTCTGAAGTGAAATACCCGGGCTCAACCTGGGAACTGCTTTGGAAACTGTGTTGCTAGAGTGCTGGAGAGGTAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAAGAACACCAGTGGCGAAGGCGGCTTACTGGACAGTAACTGACGTTGAGGCTCGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 13
    name "TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCGGACGCTTAAGTCAGTTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGATACTGGGTGTCTTGAGTACAGTAGAGGCAGGCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATTGCGAAGGCAGCTTGCTGGACTGTAACTGACGCTGATGCTCGAAAGTGTGGGTATCAAACAGG"
  ]
  node
  [
    id 14
    name "TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGCAGACGGCGATGCAAGTCTGGAGTGAAAGCCCGGGGCTCAACCCCGGGACTGCTTTGGAAACTGTATGGCTAGAGTGCTGGAGAGGCAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAAGAACACCAGTGGCGAAGGCGGCTTGCTGGACAGTAACTGACGTTCAGGCTCGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 15
    name "TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCGCAGCAAGTCTGATGTGAAAGGCAGGGGCTTAACCCCTGGACTGCATTGGAAACTGCTGTGCTTGAGTGCCGGAGGGGTAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCAGTGGCGAAGGCGGCTTACTGGACGGTAACTGACGTTGAGGCTCGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 16
    name "TACGTAGGGGGCAAGCGTTGTCCGGAATTATTGGGCGTAAAGAGTACGTAGGCGGTTTGCTAAGCGCAAGGTGAAAGGCAGTGGCTTAACCATTGTAAGCCTTGCGAACTGACAGACTTGAGTGCAGGAGAGGAAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCGGTGGCGAAGGCGGCTTTCTGGACTGTAACTGACGCTGAGGTACGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 17
    name "TACGTAGGTGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGCGTGTAGGCGGGAAGGCAAGTCAGATGTGAAAACTATGGGCTCAACCCATAGCCTGCATTTGAAACTGTTTTTCTTGAGTGCTGGAGAGGCAATCGGAATTCCGTGTGTAGCGGTGAAATGCGTAGATATACGGAGGAACACCAGTGGCGAAGGCGGATTGCTGGACAGTAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 18
    name "TACGGAGGATTCAAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGTTTGATAAGTTAGAGGTGAAATTTCGGGGCTCAACCCTGAACGTGCCTCTAATACTGTTGAGCTAGAGAGTAGTTGCGGTAGGCGGAATGTATGGTGTAGCGGTGAAATGCTTAGAGATCATACAGAACACCGATTGCGAAGGCAGCTTACCAAACTATATCTGACGTTGAGGCACGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 19
    name "TACGTAGGGTGCGAGCGTTAATCGGAATTACTGGGCGTAAAGGGTGCGCAGGCGGTTGAGTAAGACAGATGTGAAATCCCCGAGCTTAACTCGGGAATGGCATATGTGACTGCTCGACTAGAGTGTGTCAGAGGGAGGTGGAATTCCACGTGTAGCAGTGAAATGCGTAGATATGTGGAAGAACACCGATGGCGAAGGCAGCCTCCTGGGACATAACTGACGCTCAGGCACGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 20
    name "TACGTAGGTGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGCGTGTAGGCGGGATTGCAAGTCAGATGTGAAAACTGGGGGCTCAACCTCCAGCCTGCATTTGAAACTGTAGTTCTTGAGTGCTGGAGAGGCAATCGGAATTCCGTGTGTAGCGGTGAAATGCGTAGATATACGGAGGAACACCAGTGGCGAAGGCGGATTGCTGGACAGTAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 21
    name "TACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGCAGGCGGTGCGGCAAGTCTGATGTGAAAGCCCGGGGCTCAACCCCGGTACTGCATTGGAAACTGTCGTACTAGAGTGTCGGAGGGGTAAGTGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCAGTGGCGAAGGCGGCTTACTGGACGATAACTGACGCTGAGGCTCGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 22
    name "TACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGAGTGGCAAGTCTGATGTGAAAACCCGGGGCTCAACCCCGGGACTGCATTGGAAACTGTCAATCTAGAGTACCGGAGAGGTAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCAGTGGCGAAGGCGGCTTACTGGACGGTAACTGACGTTGAGGCTCGAAAGCGTGGGGAGCAAACAGG"
  ]
  node
  [
    id 23
    name "TACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGATGGGCAAGTCTGATGTGAAAACCCGGGGCTCAACCCCGGGACTGCATTGGAAACTGTTCATCTAGAGTGCTGGAGAGGTAAGTGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCAGTGGCGAAGGCGGCTTACTGGACAGTAACTGACGTTGAGGCTCGAAAGCGTGGGGAGCAAACAGG"
  ]
  edge
  [
    source 1
    target 0
    weight "-1.217"
  ]
  edge
  [
    source 2
    target 0
    weight "-0.874"
  ]
  edge
  [
    source 4
    target 3
    weight "-0.860"
  ]
  edge
  [
    source 3
    target 1
    weight "-1.574"
  ]
  edge
  [
    source 3
    target 2
    weight "-1.130"
  ]
  edge
  [
    source 5
    target 3
    weight " 0.916"
  ]
  edge
  [
    source 6
    target 4
    weight "-0.815"
  ]
  edge
  [
    source 6
    target 1
    weight "-1.493"
  ]
  edge
  [
    source 6
    target 2
    weight "-1.072"
  ]
  edge
  [
    source 6
    target 5
    weight " 0.869"
  ]
  edge
  [
    source 7
    target 1
    weight " 2.170"
  ]
  edge
  [
    source 7
    target 2
    weight " 1.557"
  ]
  edge
  [
    source 7
    target 5
    weight "-1.263"
  ]
  edge
  [
    source 8
    target 7
    weight "-1.182"
  ]
  edge
  [
    source 9
    target 1
    weight " 1.285"
  ]
  edge
  [
    source 9
    target 2
    weight " 0.923"
  ]
  edge
  [
    source 9
    target 5
    weight "-0.748"
  ]
  edge
  [
    source 10
    target 7
    weight " 0.948"
  ]
  edge
  [
    source 10
    target 4
    weight " 1.131"
  ]
  edge
  [
    source 11
    target 10
    weight " 0.781"
  ]
  edge
  [
    source 10
    target 1
    weight " 2.072"
  ]
  edge
  [
    source 10
    target 2
    weight " 1.487"
  ]
  edge
  [
    source 12
    target 10
    weight " 0.717"
  ]
  edge
  [
    source 10
    target 5
    weight "-1.206"
  ]
  edge
  [
    source 10
    target 8
    weight "-1.129"
  ]
  edge
  [
    source 13
    target 4
    weight " 0.678"
  ]
  edge
  [
    source 13
    target 1
    weight " 1.241"
  ]
  edge
  [
    source 13
    target 2
    weight " 0.891"
  ]
  edge
  [
    source 13
    target 5
    weight "-0.722"
  ]
  edge
  [
    source 7
    target 4
    weight " 1.185"
  ]
  edge
  [
    source 4
    target 1
    weight " 2.591"
  ]
  edge
  [
    source 4
    target 2
    weight " 1.859"
  ]
  edge
  [
    source 14
    target 4
    weight " 0.779"
  ]
  edge
  [
    source 12
    target 4
    weight " 0.897"
  ]
  edge
  [
    source 15
    target 4
    weight "-0.874"
  ]
  edge
  [
    source 5
    target 4
    weight "-1.508"
  ]
  edge
  [
    source 16
    target 4
    weight "-1.082"
  ]
  edge
  [
    source 8
    target 4
    weight "-1.411"
  ]
  edge
  [
    source 11
    target 7
    weight " 0.818"
  ]
  edge
  [
    source 11
    target 4
    weight " 0.977"
  ]
  edge
  [
    source 11
    target 1
    weight " 1.788"
  ]
  edge
  [
    source 11
    target 2
    weight " 1.283"
  ]
  edge
  [
    source 11
    target 5
    weight "-1.041"
  ]
  edge
  [
    source 11
    target 8
    weight "-0.974"
  ]
  edge
  [
    source 2
    target 1
    weight " 3.404"
  ]
  edge
  [
    source 16
    target 1
    weight "-1.981"
  ]
  edge
  [
    source 8
    target 1
    weight "-2.584"
  ]
  edge
  [
    source 17
    target 1
    weight "-1.270"
  ]
  edge
  [
    source 18
    target 4
    weight " 0.862"
  ]
  edge
  [
    source 18
    target 1
    weight " 1.578"
  ]
  edge
  [
    source 18
    target 2
    weight " 1.133"
  ]
  edge
  [
    source 18
    target 5
    weight "-0.918"
  ]
  edge
  [
    source 18
    target 8
    weight "-0.860"
  ]
  edge
  [
    source 16
    target 2
    weight "-1.422"
  ]
  edge
  [
    source 8
    target 2
    weight "-1.855"
  ]
  edge
  [
    source 17
    target 2
    weight "-0.911"
  ]
  edge
  [
    source 14
    target 1
    weight " 1.426"
  ]
  edge
  [
    source 14
    target 2
    weight " 1.023"
  ]
  edge
  [
    source 14
    target 5
    weight "-0.830"
  ]
  edge
  [
    source 12
    target 1
    weight " 1.642"
  ]
  edge
  [
    source 12
    target 2
    weight " 1.178"
  ]
  edge
  [
    source 12
    target 5
    weight "-0.955"
  ]
  edge
  [
    source 12
    target 8
    weight "-0.894"
  ]
  edge
  [
    source 15
    target 1
    weight "-1.601"
  ]
  edge
  [
    source 15
    target 2
    weight "-1.149"
  ]
  edge
  [
    source 15
    target 5
    weight " 0.932"
  ]
  edge
  [
    source 5
    target 1
    weight "-2.761"
  ]
  edge
  [
    source 5
    target 2
    weight "-1.981"
  ]
  edge
  [
    source 16
    target 5
    weight " 1.153"
  ]
  edge
  [
    source 8
    target 5
    weight " 1.504"
  ]
  edge
  [
    source 16
    target 8
    weight " 1.079"
  ]
  edge
  [
    source 19
    target 1
    weight "-1.222"
  ]
  edge
  [
    source 20
    target 4
    weight " 0.624"
  ]
  edge
  [
    source 20
    target 1
    weight " 1.142"
  ]
  edge
  [
    source 20
    target 2
    weight " 0.820"
  ]
  edge
  [
    source 21
    target 4
    weight "-0.842"
  ]
  edge
  [
    source 21
    target 1
    weight "-1.542"
  ]
  edge
  [
    source 21
    target 2
    weight "-1.107"
  ]
  edge
  [
    source 21
    target 5
    weight " 0.898"
  ]
  edge
  [
    source 21
    target 8
    weight " 0.840"
  ]
  edge
  [
    source 22
    target 1
    weight " 1.131"
  ]
  edge
  [
    source 23
    target 1
    weight "-1.324"
  ]
  edge
  [
    source 23
    target 2
    weight "-0.950"
  ]
]
